# Generated by Django 2.2.7 on 2019-11-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonKeeper', '0002_student_parent_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='student',
        ),
        migrations.AddField(
            model_name='contact',
            name='student',
            field=models.ManyToManyField(to='lessonKeeper.Student'),
        ),
    ]
