# Generated by Django 2.2.7 on 2019-11-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonKeeper', '0003_auto_20191106_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='parent_name',
        ),
        migrations.AddField(
            model_name='contact',
            name='parent_name',
            field=models.ManyToManyField(to='lessonKeeper.Student'),
        ),
        migrations.RemoveField(
            model_name='contact',
            name='student',
        ),
        migrations.AddField(
            model_name='contact',
            name='student',
            field=models.CharField(default='', max_length=100),
        ),
    ]
