# Generated by Django 2.2.7 on 2019-11-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonKeeper', '0005_auto_20191106_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parent_name',
        ),
        migrations.AddField(
            model_name='contact',
            name='relationship',
            field=models.CharField(default='Parent', max_length=180),
        ),
    ]
