# Generated by Django 2.2.7 on 2019-11-06 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessonKeeper', '0006_auto_20191106_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='parent_name',
            new_name='contact_name',
        ),
    ]
