# Generated by Django 2.2.7 on 2019-11-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonKeeper', '0008_auto_20191106_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='contacts', to='lessonKeeper.Student'),
        ),
    ]
